### ISSUE TITLE
p5Events not defined

### ISSUE THREAD

**Issue by shellby1** [Kinrany/vue-p5#15]
File: p5.vue
  Line: 44 
    "p5Events() {" should be "p5Events: function() {";
  Line: 55
    "for (const p5EventName of p5Events) {" should be "for (const p5EventName of this.p5Events) {"

**Comment by Kinrany** [comment]
Thank you for the report, I'll fix this ASAP.

**Comment by Kinrany** [comment]
I pulled `0.8.x-rc1` and published `0.8.x-rc2` with a fix.

`vue-p5@latest` now points to `0.7.1` as it should. You might want to use `vue-p5@next` if you need `p5@0.9.0` or `windowResized`.

**Comment by Kinrany** [comment]
And thanks again for letting me know about this. I really need to add minimal tests and CI checks here.
