### ISSUE TITLE
Event names to camelCase to be identical of P5JS API

### ISSUE THREAD

**Issue by nestarz** [Kinrany/vue-p5#23]
https://github.com/Kinrany/vue-p5/blob/ed2dde5f3849f4da91480aba563f789ffc27ea01/src/p5.vue#L63

From:
`          this.$emit(vueEventName, sketch, ...args);
`
To:
`          this.$emit(p5EventName, sketch, ...args);
`

What do you think ?

**Comment by nestarz** [comment]
No we should not:

https://vuejs.org/v2/guide/components-custom-events.html

**Comment by Kinrany** [comment]
Yeah, unfortunately using p5 event names for Vue events is not an option: there would be no way to subscribe to them :(
