### ISSUE TITLE
TypeError: sketch.createCapture is not a function

### ISSUE THREAD

**Issue by khuqen** [Kinrany/vue-p5#24]
Error in v-on handler: "TypeError: sketch.createCapture is not a function"

when i using sketch.createCapture function
```js
    setup(sketch) {
      sketch.createCanvas(960, 540);
      let constraints = {
        video: {
          mandatory: {
            minWidth: 1920,
            minHeight: 1080
          },
          optional: [{ maxFrameRate: 10 }]
        },
        audio: false
      };
      sketch.line(100, 200, 200, 300);
      this.capture = sketch.createCapture(constraints);
    }
```

**Comment by Kinrany** [comment]
Hi, thanks for the report!

Could you try using `vue-p5@next` and see if that works?

If you're using a script, it's `<script src="https://unpkg.com/vue-p5@next"></script>`

**Comment by Kinrany** [comment]
`vue-p5@0.8.2` is out, so this should be fixed now.
