### ISSUE TITLE
`windowResized` may not be called as expected

### ISSUE THREAD

**Issue by agm1984** [Kinrany/vue-p5#30]
Hey I'm having an issue with the `windowResized`  event.

``` vue
        <vue-p5
            :additionalEvents="['windowResized']"
            @setup="setup"
            @draw="draw"
            @windowResized="windowResized"
        ></vue-p5>
```

These don't work for me. I found this issue thread: https://github.com/Kinrany/vue-p5/issues/11

In here, you recommended:

``` javascript
            document.addEventListener('resize', () => {
                sketch.resizeCanvas(window.innerWidth, window.innerHeight);
            });
```

That also doesn't work for me, and the issue is that `document.addEventListener()` doesn't work. When I change it to `window`, it starts working and correctly fires the `resize` event.

I figured I would make an issue for this in case anyone else encounters this. It will probably affect the generic/edge cases around `:additionalEvents="[]"` if it is calling `document.` in the library code.

Beyond that, nice work. I just ported over an ancient vanilla JavaScript "sacred geometry" generator, and the code is so much nicer to work with now via _vue-p5_.

Bonus note: I have read about this before, where sometimes document works and other times window works, depending on the browser/client/environment. This is the first time I've encountered it in the wild.

My naive idea would be to perform some kind of check like:

``` javascript
if (typeof document.addEventListener === 'function') {
    // k
} else {
    // use window
}
```

I did test that for a couple seconds in my browser here, and even though `document` doesn't work, addEventListener still exists on it, so that might be a first hurdle. It would be nice to find a way to programmatically settle what exactly is resizing, and then slap the listeners on that. I figured I'd add that bonus to wet your mojo a little bit.

**Comment by Kinrany** [comment]
Hi, thanks for the kind words!

Please try lowercase `@windowresized` instead of `@windowResized`. Also it's already supported, so you don't need `:additionalEvents`!

This is a gotcha multiple people have already had issues with, so I guess it's finally time for me to add FAQ :D

**Comment by agm1984** [comment]
Thanks for the turbo reply velocity. I just tried and that did work. Thanks a lot.

**Comment by Kinrany** [comment]
You're welcome 🙂
